/*
=========================================================
Healthcare CRM SQL Analysis
File: 07_executive_reporting.sql

Objective:
Create executive-level reports that support strategic
decision-making within a healthcare organisation.
=========================================================
*/

USE healthcare_crm_analysis;

-- Executive Report 1
-- Top 10 highest-value patients

SELECT
    p.patient_id,
    CONCAT(p.first_name,' ',p.last_name) AS patient_name,
    ROUND(SUM(b.amount),2) AS lifetime_value
FROM patients p
INNER JOIN billing b
ON p.patient_id = b.patient_id
GROUP BY
    p.patient_id,
    patient_name
ORDER BY lifetime_value DESC
LIMIT 10;

-- Executive Report 2
-- Top-performing doctors by generated revenue

SELECT
    CONCAT(d.first_name,' ',d.last_name) AS doctor_name,
    d.specialization,
    ROUND(SUM(t.cost),2) AS revenue_generated
FROM doctors d
INNER JOIN appointments a
ON d.doctor_id = a.doctor_id
INNER JOIN treatments t
ON a.appointment_id = t.appointment_id
GROUP BY
    doctor_name,
    d.specialization
ORDER BY revenue_generated DESC;

-- Executive Report 3
-- Revenue generated by treatment type

SELECT
    treatment_type,
    ROUND(SUM(cost),2) AS total_revenue
FROM treatments
GROUP BY treatment_type
ORDER BY total_revenue DESC;

-- Executive Report 4
-- Revenue by payment status

SELECT
    payment_status,
    ROUND(SUM(amount),2) AS total_amount
FROM billing
GROUP BY payment_status
ORDER BY total_amount DESC;

-- Executive Report 5
-- Top 10 patients by appointment activity

SELECT
    CONCAT(p.first_name,' ',p.last_name) AS patient_name,
    COUNT(a.appointment_id) AS appointments
FROM patients p
INNER JOIN appointments a
ON p.patient_id = a.patient_id
GROUP BY
    patient_name
ORDER BY appointments DESC
LIMIT 10;
